#!/bin/bash
pip3 install torch
pip3 install torchvision
pip3 install opencv-python
pip3 install torchnet
pip3 install tqdm
pip3 install torchsummary
pip3 install matplotlib
pip3 install fire
pip3 install sklearn
pip3 install torch
pip3 install torchvision
pip3 install opencv-python
pip3 install torchnet
pip3 install tqdm
pip3 install torchsummary
pip3 install matplotlib
pip3 install fire
pip3 install sklearn
