from .BasicModule import MyVgg11Net
from .BasicModule import MyVgg13Net
from .BasicModule import MyVgg16Net
from .BasicModule import MyVgg19Net
from .BasicModule import MyresNet18
from .BasicModule import MyresNet34
from .BasicModule import MyresNet50
from .BasicModule import MyInceptionV3
from .BasicModule import MydenseNet121
from .BasicModule import MydenseNet161
from .BasicModule import MydenseNet169
from .BasicModule import MydenseNet201
from .BasicModule import MyseNet1_0
from .BasicModule import MyseNet1_1
from .BasicModule import MultiscaleresNet18
