from .BasicModule import MyVggNet11
from .BasicModule import MyVggNet13
from .BasicModule import MyVggNet16
from .BasicModule import MyVggNet19
from .BasicModule import MyresNet18
from .BasicModule import MyresNet34
from .BasicModule import MyresNet50
from .BasicModule import MyInceptionV3
from .BasicModule import MydenseNet121
from .BasicModule import MydenseNet161
from .BasicModule import MydenseNet169
from .BasicModule import MydenseNet201
from .BasicModule import MyseNet1_0
from .BasicModule import MyseNet1_1
from .BasicModule import Myxception
from .BasicModule import MydetNet59
from .BasicModule import MynasNet
from .BasicModule import MultiscaleresNet18
